### ISSUE TITLE
Uninstalling K3S from the servers.

### ISSUE THREAD

**Issue by Nahum48** [carlosedp/cluster-monitoring#102]
Hi,

How do i uninstall the K3S from the servers?
i looked for un install script but i couldn't find one....

if you know the location, i'll be happy for your reply. :)

**Comment by mrmillers** [comment]
Does ```make teardown``` work for you?

**Comment by Nahum48** [comment]
Thanks, but already restored my servers.

**Comment by carlosedp** [comment]
Check K3s documentation, it creates an uninstall script.
Closing.
