### ISSUE TITLE
prometheus-alertmanager and prometheus-server at constant pending on Nvidia Jetson Nano

### ISSUE THREAD

**Issue by organicnz** [carlosedp/cluster-monitoring#103]
Looks like NVIDIA Jetson Nano doesn't digest the Docker image at this point it hangs on constant pending, unfortunately. Is there any chance to fix it out or it's only compatible with the RPI4 for now? :)

```
prometheus-alertmanager-68b54d8dc7-dnjw4 0/2 Pending 0 3d8h
prometheus-server-5975958bf5-467d6 0/2 Pending 0 3d8h
```

Hardware: NVIDIA Jetson Nano
OS: Ubuntu 18.04.5 LTS (GNU/Linux 4.9.140-tegra aarch64)

**Comment by carlosedp** [comment]
It should be compatible with any ARM64 board.
Check more details (kubectl describe and logs) on the pods to understand why it's pending.

**Comment by organicnz** [comment]
Thanks, mate, I'm gonna investigate it for more details :)

**Comment by carlosedp** [comment]
Any news on this?
