### ISSUE TITLE
Missing Service when adding arm-exporter

### ISSUE THREAD

**Issue by robwilkes** [carlosedp/cluster-monitoring#11]
I'm not a go or jsonnet person, so reporting here.
When building and adding arm-exporter for temps, the resulting yaml is missing a couple things.

arm-exporter-serviceAccount.yaml (file missing, needed, for me at least):
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arm-exporter
  namespace: monitoring

along with:
arm-exporter-daemonset.yaml:
add: serviceAccountName: arm-exporter
and: tls-cipher-suites

Without the service account and the serviceAccountName added to the daemonset, I was getting 401 unauthorized errors.

Wish there was more I could do to help, this project is aweosme

**Comment by carlosedp** [comment]
Hi Rob, thanks for the issue. 

Can you please test with the issue-11 branch by checking it out with `git clone -b issue-11 https://github.com/carlosedp/cluster-monitoring`?

**Comment by carlosedp** [comment]
Fixed on PR #12
