### ISSUE TITLE
Two (not related) Prometheus instances

### ISSUE THREAD

**Issue by jamessewell** [carlosedp/cluster-monitoring#113]
Love this repo!

I am trying to work out how I deploy two Proms in one namespace (one will be for k8s, and the other will be for app data - with different retentions).

I thought this would work:

```
 prometheus+:: {
    // Add option (from vars.yaml) to enable persistence
    local pvc = k.core.v1.persistentVolumeClaim,
    apps+: {
      spec+: {
...
...
   prometheus+: {
      spec+: {
```

But I only get the storage stuff in ./manifests/prometheus-apps.yaml, not the rest.

Any ideas?

I'm hoping to have a service and grafana datasource for each.

**Comment by carlosedp** [comment]
This monitoring stack was not planned to have multiple Prometheus instances on the same namespace. I suggest having them separately.

**Comment by jamessewell** [comment]
The issue is that you can’t really run multiple Prometheus operators in a
cluster - so another instance kinda has to be integrated.
