### ISSUE TITLE
missing go.mod file

### ISSUE THREAD

**Issue by sadesguy** [carlosedp/cluster-monitoring#157]
**Describe the bug**
followed the quickstart guide and encountered a missing file

**Troubleshooting**

1. K3s

**Customizations**

1. Yes 

```jsonnet
   name: 'armExporter',
      enabled: true,
      file: import 'modules/arm_exporter.jsonnet',
      
       k3s: {
    enabled: true,
```

2. no

**Comment by carlosedp** [comment]
There is no Golang code in the project, it might be something missing in the required tools (gojsontoyaml or jsonnet compiler).
