### ISSUE TITLE
Investigate the use of kube-rbac-proxy on K3s

### ISSUE THREAD

**Issue by carlosedp** [carlosedp/cluster-monitoring#16]
Dive deeper on kube-rbac-proxy use of the API on K3s to return endpoints into https and authenticated endpoints.

Ref. https://github.com/carlosedp/cluster-monitoring/issues/13

**Comment by hlugt** [comment]
As replied in https://github.com/rancher/k3s/issues/425 I tried the new manifests (I only changed the external addresses to my own). I now do have node-exporter connections and metrics, but the k3s kubelet and cadvisor still give connection refused (Get http://#.#.#.#:10255/metrics: dial tcp #.#.#.#:10255: connect: connection refused and Get http://#.#.#.#:10255/metrics/cadvisor: dial tcp #.#.#.#:10255: connect: connection refused).

I just updated to the latest release of K3S: curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=v0.10.2 INSTALL_K3S_EXEC="--no-deploy traefik --no-deploy=servicelb" sh -s - --kubelet-arg="authentication-token-webhook=true" --kubelet-arg="authorization-mode=Webhook" --kubelet-arg="address=0.0.0.0"

Maybe I should by now get rid of the extra kubelet arguments?

**Comment by carlosedp** [comment]
Latest version supports the use of kube-rbac-proxy on kube-state-metrics and node_exporter.

<img width="1520" alt="image" src="https://user-images.githubusercontent.com/20382/76969845-bc1f2000-6909-11ea-8e73-7453316de6fa.png">
