### ISSUE TITLE
Not a bug - more of a configuration problem with Grafana Datasource out of the box or my understanding of k3s

### ISSUE THREAD

**Issue by Dowster64** [carlosedp/cluster-monitoring#169]
Hi,
I have started a k3s raspberry pi 4 cluster and following Jeff Geerling's video was able to install this 'instance'.  However the custom dashboard shows bad gateway for all of the widgets. 
It was necessary to create a new prometheus datasource with the settings for my local system (which you can test and save).  It might be worth adding that info for tyros like me?  The correct url was found from the targets page on prometheus
Thanks,
Steve

**Comment by carlosedp** [comment]
Would you elaborate and maybe send a PR to the readme?
Thanks.
