### ISSUE TITLE
Some metrics from cadvisor have no data on K3s

### ISSUE THREAD

**Issue by carlosedp** [carlosedp/cluster-monitoring#17]
Due to different runtime use by K3s, cadvisor does not report some metrics due to missing fields.

Ref: 
* https://github.com/rancher/k3s/issues/473#issuecomment-523558249
* https://github.com/google/cadvisor/issues/2249

**Comment by geekdave** [comment]
Looks like k3s supports running using docker instead of containerd:

> k3s includes and defaults to containerd. Why? Because it’s just plain better. If you want to run with Docker first stop and think, “Really? Do I really want more headache?” If still yes then you just need to run the agent with the `--docker` flag.

https://rancher.com/docs/k3s/latest/en/configuration/#containerd-and-docker

I'll give this a try soon and see if it resolves the issue.

**Comment by carlosedp** [comment]
Deploying K3s with Docker as the runtime with `k3s server --docker` makes all metadata available in metrics.

![](https://user-images.githubusercontent.com/20382/63546683-be9ad200-c500-11e9-8fda-1e22edd4c947.png)

**Comment by carlosedp** [comment]
Tested on K3s v0.10.2 and metrics are generated without requiring `--docker` as runtime.
