### ISSUE TITLE
K3s - Disappearing metrics

### ISSUE THREAD

**Issue by NicklasWallgren** [carlosedp/cluster-monitoring#20]
I have noticed that the  `kube-controller-manager` and the `kube-scheduler` disappears from the list of targets in `prometheus` after 12-24 hours. The metrics endpoints it still available thought.

I have tried to restart the prometheus container, but to no avail. The only solution so far it to re-apply the manifest-files.

Thanks for a great repo!

![image](https://user-images.githubusercontent.com/1784879/65437594-62d7a780-de24-11e9-86a2-5b56eb30c139.png)
![image](https://user-images.githubusercontent.com/1784879/65437688-87338400-de24-11e9-8953-3c76e40bfa55.png)

**Comment by NicklasWallgren** [comment]
The `kube-controller-manager-prometheus-discovery` and `kube-scheduler-prometheus-discovery` endpoints are missing their endpoint-address. 

The seems like the addresses is cleared, regularly.

```
traefik                                        50.42.0.18:80,50.42.0.18:8080,50.42.0.18:443                             46h
kubelet                                        10.144.100.86:10255,10.144.100.87:10255,10.144.100.86:4194 + 3 more...   44h
kube-dns-prometheus-discovery                  50.42.0.19:9153                                                          44h
kube-controller-manager-prometheus-discovery   <none>                                                                   44h
kube-dns                                       50.42.0.19:53,50.42.0.19:53,50.42.0.19:9153                              46h
kube-scheduler-prometheus-discovery            <none>                                                                   44h
```

**Comment by carlosedp** [comment]
That's weird since both are created by the stack and shouldn't vanish. I saw a duplicate in the k3s. Will be fixed it on next commit. I'm gonna keep an eye on the endpoints.

**Comment by carlosedp** [comment]
I haven't seen this behavior repeat. Can this be closed @NicklasWallgren ?

**Comment by NicklasWallgren** [comment]
@carlosedp 
I'm still seeing the behavior in multiple clusters. Probably related to k3s and/or kubernetes.

You can close this issue.

**Comment by NicklasWallgren** [comment]
@carlosedp On another note, is the grafana-dashboard updated to support k3s 0.10+/k8s 1.16.2+?

See 
https://github.com/coreos/kube-prometheus/issues/284
https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/274/files
https://github.com/helm/charts/issues/18377

Thanks

**Comment by carlosedp** [comment]
Just updated libs on f857930.

**Comment by NicklasWallgren** [comment]
For reference https://github.com/rancher/k3s/issues/1562
