### ISSUE TITLE
metrices for some namespaces are missing

### ISSUE THREAD

**Issue by uocxp** [carlosedp/cluster-monitoring#26]
The metrices for the pods on some namespaces are not there. Actually only the metrices for the kube-system and metallb namespaces are present (although without the metrices fort Network I/O). When i check the cpu and memory usage using `kubectl top pod foo` i can prove that the pods are using  memory and cpu.
How can i debug the problem?

I am using kubernetes 1.15.5 on a raspberrypi cluster
![image](https://user-images.githubusercontent.com/8387383/73177011-25ef2a80-410e-11ea-80ff-82b7d9a4afd4.png)

**Comment by carlosedp** [comment]
can you try to update the upstream libraries checking-out the repo, issuing a `make update` and then building the manifests and apply them.
Sometimes the metric names change between K8s versions and the libraries need to be updated.

**Comment by carlosedp** [comment]
Any news on this? Could you retest @uocxp?

**Comment by uocxp** [comment]
I actually decided the next day for the helm chart instead. I needed though to cross-build some images for ARM since the chart contains mostly non-arm compatible docker images.
