### ISSUE TITLE
Redirect to HTTPS version when connecting over Load Balancer Ingress

### ISSUE THREAD

**Issue by L0g4n** [carlosedp/cluster-monitoring#28]
Hi,
first of all, thanks for your work, I tested your manifest with my local k3s cluster and while it is not a perfect setting it works better than the standard prometheus-operator that is geared towards k8s.
I noticed that all services get exposed via TLS via the ingress, but it does not automatically redirect one to the HTTPS version of the site when you connect to the HTTP version of your service. This should be configurable via a setting in the ingress, I guess.

**Comment by L0g4n** [comment]
I have not much experience in jsonnet, but after some googling I found the ksonnetapi to do the necessary changes, see #29. Basically, it just adds the host name to the "tls" key in the ingress. After these changes I get automatically redirected to the HTTPS version of the service.

**Comment by carlosedp** [comment]
Closed by #29.
Thanks!
