### ISSUE TITLE
Grafana pod not starting 

### ISSUE THREAD

**Issue by serverbaboon** [carlosedp/cluster-monitoring#31]
I have tried this project on my Raspberry 4 Arm64 K3s cluster running k3s on unbuntu 19..10.

When I ran without persistant storage everything seemed to work great, I then tried to deploy with perstistent  storage on my Ceph cluster publishing block storage, then the  grafana  fails to launch with the below error.

GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-from-a-previous-version-of-the-docker-container-to-5-1-or-later
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied

Below is my vars.jsonnet file

{
  _config+:: {
    namespace: 'monitoring',
  },
  // Enable or disable additional modules
  modules: [
    {
      // After deployment, run the create_gmail_auth.sh script from scripts dir.
      name: 'smtpRelay',
      enabled: false,
      file: import 'smtp_relay.jsonnet',
    },
    {
      name: 'armExporter',
      enabled: true,
      file: import 'arm_exporter.jsonnet',
    },
    {
      name: 'upsExporter',
      enabled: false,
      file: import 'ups_exporter.jsonnet',
    },
    {
      name: 'metallbExporter',
      enabled: false,
      file: import 'metallb.jsonnet',
    },
    {
      name: 'traefikExporter',
      enabled: true,
      file: import 'traefik.jsonnet',
    },
    {
      name: 'elasticExporter',
      enabled: false,
      file: import 'elasticsearch_exporter.jsonnet',
    },
  ],

  k3s: {
    enabled: true,
    master_ip: ['192.168.5.41'],
  },

  // Domain suffix for the ingresses
  suffixDomain: 'example.com',
  // If TLSingress is true, a self-signed HTTPS ingress with redirect will be created
  TLSingress: true,
  // If UseProvidedCerts is true, provided files will be used on created HTTPS ingresses.
  // Use a wildcard certificate for the domain like ex. "*.192.168.99.100.nip.io"
  UseProvidedCerts: false,
  TLSCertificate: importstr 'server.crt',
  TLSKey: importstr 'server.key',

  // Setting these to false, defaults to emptyDirs
  enablePersistence: {
    prometheus: true,
    grafana: true,
  },

  // Grafana "from" email
  grafana: {
    from_address: 'myemail@gmail.com',
  },
}

**Comment by carlosedp** [comment]
Could you try applying the patch below to the cluster-monitoring tree, rerun `make` and apply to the cluster to check if it works?

```
patch -p1 --ignore-whitespace << 'EOF'
diff --git a/base_operator_stack.jsonnet b/base_operator_stack.jsonnet
index 086db91..eb9c9fc 100644
--- a/base_operator_stack.jsonnet
+++ b/base_operator_stack.jsonnet
@@ -92,6 +92,10 @@ local vars = import 'vars.jsonnet';
       spec+: {
         template+: {
           spec+: {
+            securityContext: {
+              runAsUser: 472,
+              runAsNonRoot: true,
+            },
             volumes:
               std.map(
                 function(v)
EOF
```

**Comment by serverbaboon** [comment]
Sure just give me a day or so  had power off and move the cluster for home working.being imposed..

**Comment by serverbaboon** [comment]
Hi sorry for the delay, no that did not work.

Let me play around with K3s versions and try the Local Storage provider to see if its related to Ceph.

**Comment by serverbaboon** [comment]
Ok it works with K3s 1.17.4 and the Local-Storage provider that is the default storage option so its something to do with my Ceph cluster. I will do some research on this to see if I need to adjust my Ceph Cluster (block).

**Comment by carlosedp** [comment]
Nice, let me know.

**Comment by serverbaboon** [comment]
Ok I modified the Grafana-deploy.yaml by adding in the fsgroup parameter, I need to understand why I need this extra parameter but the below works.

      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472

**Comment by carlosedp** [comment]
Because the image is built and run with a user with the ID 472 according to the documentation. So when we run the container, Kubernetes(or K3s) needs to run it with this user ID.

**Comment by serverbaboon** [comment]
...yeah, was more why the fsGroup was also needed as well as runAsUser especially as the uids are the same.

I am wondering whether the fact that my cluster is using the flex drivers which I need to use due to csi drivers for arm64 availability issues.

Anyway now seems to be working for me now.
