### ISSUE TITLE
Prometheus Operator Helm chart w/ k3s

### ISSUE THREAD

**Issue by onedr0p** [carlosedp/cluster-monitoring#32]
Hi, question. I am already using the Prometheus Operator Helm Chart in my k3s cluster. I would like to get kubeControllerManager and kubeScheduler monitored, what is the work that needs to be done to enable this without using your deployments here? Is it possible?

**Comment by carlosedp** [comment]
You need to add the endpoints to your cluster. See my https://github.com/carlosedp/cluster-monitoring/blob/master/k3s-overrides.jsonnet file.
