### ISSUE TITLE
PersistentVolume pointed at specific location (e.g. NFS server)

### ISSUE THREAD

**Issue by DrumSergio** [carlosedp/cluster-monitoring#35]
Is there a way to "easily" point to a pv/pvc in order to have real persistant storage in my k3s cluster?

Sorry it's not an issue, but a question. Maybe a feature request :)

PS. Is there a way to easily uninstall all of it without going one-by-one deleting all resources? Thank you!

**Comment by carlosedp** [comment]
You can enable a flag that makes the stack create a PV/PVC in some StorageClass. You can't use an existing one.
Yes, `make teardown`
