### ISSUE TITLE
Unable to access dashboards

### ISSUE THREAD

**Issue by werne2j** [carlosedp/cluster-monitoring#44]
I attempted to deploy to my rasperry pi cluster running k3s and i am unable to reach the dashboards. I was thinking maybe something with my k3s setup was wrong so i attempted to re-deploy k3s but am still seeing the same issue. 

```
{
  ...
  modules: [
    {
      // After deployment, run the create_gmail_auth.sh script from scripts dir.
      name: 'smtpRelay',
      enabled: false,
      file: import 'smtp_relay.jsonnet',
    },
    {
      name: 'armExporter',
      enabled: true,
      file: import 'arm_exporter.jsonnet',
    },
    {
      name: 'upsExporter',
      enabled: false,
      file: import 'ups_exporter.jsonnet',
    },
    {
      name: 'metallbExporter',
      enabled: false,
      file: import 'metallb.jsonnet',
    },
    {
      name: 'traefikExporter',
      enabled: true,
      file: import 'traefik.jsonnet',
    },
    {
      name: 'elasticExporter',
      enabled: false,
      file: import 'elasticsearch_exporter.jsonnet',
    },
  ],

  k3s: {
    enabled: true,
    master_ip: ['<my-ip>'],
  },

  // Domain suffix for the ingresses
  suffixDomain: '<my-ip>.nip.io',
  // If TLSingress is true, a self-signed HTTPS ingress with redirect will be created
  TLSingress: true,
  ...
}

**Comment by barrygear** [comment]
I just tried this today on my k3s cluster. I had to run `make deploy` twice for it to successfully installed. I did not use <my-ip_.nip.io but <my-clustername>.lan. Afterwards I noticed the installation created an ingress called grafana.<my-clustername>.lan. I was able to login and view the dashboards.

**Comment by sosimon** [comment]
I had issues here too, but ran some `dig`s and turns out the DNS on my machine wasn't resolving `<my-ip>.nip.io` properly.  I explicitly set my DNS to `8.8.8.8` (Google's) and it works fine. YMMV

**Comment by werne2j** [comment]
> I had issues here too, but ran some `dig`s and turns out the DNS on my machine wasn't resolving `<my-ip>.nip.io` properly.  I explicitly set my DNS to `8.8.8.8` (Google's) and it works fine. YMMV

This worked for me as well. Thanks for the help
