### ISSUE TITLE
Error when running 'make'

### ISSUE THREAD

**Issue by 22367rh** [carlosedp/cluster-monitoring#53]
While running make I eventually get this in the console:

```
rm -rf manifests
./scripts/build.sh main.jsonnet /root/go/bin/jsonnet
using jsonnet from arg
+ set -o pipefail
+ rm -rf manifests
+ mkdir -p manifests/setup
+ /root/go/bin/jsonnet -J vendor -m manifests main.jsonnet
+ xargs '-I{}' sh -c 'cat {} | $(go env GOPATH)/bin/gojsontoyaml > {}.yaml; rm -f {}' -- '{}'
./scripts/build.sh: line 23:  7595 Killed                  $JSONNET_BIN -J vendor -m manifests "${1-example.jsonnet}"
      7596 Done                    | xargs -I{} sh -c 'cat {} | $(go env GOPATH)/bin/gojsontoyaml > {}.yaml; rm -f {}' -- {}
make: *** [Makefile:19: manifests] Error 137
```

My vars.jsonnet edits from default are:
* armExporter : true
* k3s.enabled : true
* k3s.master_ip : 192.168.178.82
* suffixDomain : 192.168.178.84.nip.io

Any ideas what is causing this or how to get this to run?

**Comment by 22367rh** [comment]
Ignore this. Sorry for the noise. 

Turns out Error 137 is an out of memory issue which will be due to the fact I was attempting to run it on an SBC with only 512mb Ram.

Will wait until my RPi4 with 8GB ram arrives.

**Comment by curtisspendlove** [comment]
I just spent a couple hours debugging this...until I finally thought; hmmm, I wonder if anyone else is having this issue.

I'm wondering if maybe an entry in the FAQ of the `README` is appropriate?

**Comment by AM6331** [comment]
I fixed this error by making the swapfile 2GB in size
