### ISSUE TITLE
How to regenerate grafana.ini after sercret update?

### ISSUE THREAD

**Issue by zoide** [carlosedp/cluster-monitoring#57]
Hi, I have edited the grafana-config secret to enable basic.auth.
I do not understand how to regenerate the grafana.ini with this change. I have deleted the pod, it was recreated, but the config is still the old one.

Please help, and thanks for the great work!
Cheers,
udo.

**Comment by carlosedp** [comment]
I believe one option would be editing `base_operator_stack.jsonnet` parameters here:

https://github.com/carlosedp/cluster-monitoring/blob/9b175416072d29e207977637d0aac8592d1d8d57/base_operator_stack.jsonnet#L44

And re-generating the manifests.

**Comment by zoide** [comment]
Thanks,

I've changed those vaules and had to update only the manifeste/grafana-config.yaml file. Afterwards I deleted the grafana pod. 
That changed the values.

**Comment by carlosedp** [comment]
Great!

**Comment by prasenforu** [comment]
Hi 

for me its saying  "Invalid Username or Password"  I took username as admin

**Comment by prasenforu** [comment]
my details as follows ...

```
grafana.ini: |
  [auth.anonymous]
  enabled = false
  [auth.basic]
  enabled = true
  [session]
  provider = memory
  [smtp]
  enabled = true
  from_address = myemail@gmail.com
  from_name = Grafana Alert
  host = smtp-server.monitoring.svc:25
  password = 12345678
  skip_verify = true
  user = pkar
```

same for if I use different user

**Comment by zoide** [comment]
Use the same username/password that you use to log in via the web-interface.
I needed this in order to access the http-api. It doesn't change the behaviour of the web-frontend. 
You might have a different issue here.

**Comment by prasenforu** [comment]
@zoide Thanks ..
