### ISSUE TITLE
Additional module not deployed

### ISSUE THREAD

**Issue by Gory19** [carlosedp/cluster-monitoring#58]
Hi,
I modified the vars file and set "true" on arm_exporter and metallbexporter but in the end it did not deploye.
Also when I change the IP in "suffixdomains" example 192.168.1.2, after I deployed the IP is not changed and remains 192.168.15.15.
I think it just ignores the changes to the vars.jsonnet file.

**Comment by carlosedp** [comment]
Check-out the readme.
You need to re-generate the manifests with `make` then `make deploy` after changing `vars.jsonnet`.

**Comment by Gory19** [comment]
> Check-out the readme.
> You need to re-generate the manifests with `make` then `make deploy` after changing `vars.jsonnet`.
OMG perdona la mia stupidità.
Now works.
But what if I want to use SMTP Relay? If I put "true", I get error:
"RUNTIME ERROR: Field does not exist: smtpRelay
	main.jsonnet:38:32-47	thunk from <$>
	<std>:1293:24-25	thunk from <function <anonymous>>
	<std>:1293:5-33	function <anonymous>
	main.jsonnet:38:15-48	$
		
		builtin function <flatMap>
		
	During evaluation	

make: *** [manifests] Error 1"

**Comment by Gory19** [comment]
> Check-out the readme.
> You need to re-generate the manifests with `make` then `make deploy` after changing `vars.jsonnet`.

OMG forgives my stupidity. Now works.
But what if I want to use SMTP Relay? If I put "true", I get error:
"RUNTIME ERROR: Field does not exist: smtpRelay
	main.jsonnet:38:32-47	thunk from <$>
	<std>:1293:24-25	thunk from <function <anonymous>>
	<std>:1293:5-33	function <anonymous>
	main.jsonnet:38:15-48	$
		
		builtin function <flatMap>
		
	During evaluation	

make: *** [manifests] Error 1"

**Comment by carlosedp** [comment]
Fixing it right now. Thanks for finding this out :)
