### ISSUE TITLE
prometheus command line options

### ISSUE THREAD

**Issue by zoide** [carlosedp/cluster-monitoring#59]
Hi again, here's my next issue:

I'd like to access prometheus' admin-api. It is enabled via the command line option '--web.enable-admin-api'
I found: https://github.com/coreos/prometheus-operator/pull/2300 which should enable this feature.

I have changed base_operator_stack.jsonnet and added "enableAdminAPI: 'true'". I have re-created and re-applied the manifests. Unfortunatly the commandline option is still not there on the prometheus-pod.

**Comment by carlosedp** [comment]
You should be able to add it right below `externalUrl` in:

https://github.com/carlosedp/cluster-monitoring/blob/cd17208e4fb756d4af2ea71d55d223ff7cc7eca4/base_operator_stack.jsonnet#L71-L75

Like

```jsonnet
      spec+: {
               replicas: $._config.prometheus.replicas,
               retention: '15d',
               externalUrl: 'http://' + $._config.urls.prom_ingress,
			   enableAdminAPI: "true",
             }
```

And re-generate the manifests.

**Comment by carlosedp** [comment]
Closing this. Reopen if some error is found.
