### ISSUE TITLE
The secret `ingress-TLS-secret` is invalid...

### ISSUE THREAD

**Issue by christian-schlichtherle** [carlosedp/cluster-monitoring#66]
``` bash
servicemonitor.monitoring.coreos.com/traefik created
The Secret "ingress-TLS-secret" is invalid: metadata.name: Invalid value: "ingress-TLS-secret": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
make: *** [deploy] Error 1
```

**Comment by christian-schlichtherle** [comment]
After searching for `ingress-TLS-secret` and replacing it with `ingress-secret` (TLS is redundant information) it works like a charm again.

**Comment by carlosedp** [comment]
It should work in the master branch. Have you tested it?
It was fixed (in theory) on https://github.com/carlosedp/cluster-monitoring/commit/b617576d64b1f5da5215facdf872dfc6cd260e3c

**Comment by christian-schlichtherle** [comment]
No, this commit just ensures that the passed name is used, which is `ingress-TLS-secret`. However, the error message states that this is not a valid name. After fixing as said above, it works.
