### ISSUE TITLE
How to enable grafana-piechart-panel

### ISSUE THREAD

**Issue by module0x90** [carlosedp/cluster-monitoring#67]
Hi,

I need to enable this plugin (and potentially others), I have added it to vars.jsonnet

  // Grafana "from" email
  grafana: {
    from_address: 'myemail@gmail.com',
    plugins: [
      "grafana-piechart-panel",
    ],
  },

but a make vendor/make/deploy doesn't get it enabled.
How can I get this done properly please?

Regards

Tom

**Comment by carlosedp** [comment]
Gonna check this.

**Comment by carlosedp** [comment]
Please check this.
