### ISSUE TITLE
Support for dynamic persistent volume claims

### ISSUE THREAD

**Issue by simonspg** [carlosedp/cluster-monitoring#68]
A convenient enhancement would be support for dynamic persistent storage.  storageClassName instead of volumeName.

**Comment by carlosedp** [comment]
It is. If you enable persistence and don't specify the PV names, the stack PVCs asks a PV for the default StorageClass.

**Comment by simonspg** [comment]
Agreed.  I wondered if I was being clear enough.  I’m still learning all the terminology.  What if I want to establish a dynamic persistent volume claim for a storageClass that is not the default?  K3s comes with local-path as the default storage class, and I have added the managed-nfs-storage storageClass.  I’m not sure if k3s uses local-path storage, so I left it as the default.

**Comment by carlosedp** [comment]
Added on ad1d165.
You can define the StorageClass name.
