### ISSUE TITLE
no cpu_temperature on rpi cluster

### ISSUE THREAD

**Issue by Henrik-Wo** [carlosedp/cluster-monitoring#69]
Hi,
thanks for the great wort! I run your monitoring stack on my RPI4 cluster with k3s and for the most parts it works really well. Only the cpu temperature monitoring doesn't work on my cluster. In the grafana dashboard "Kubernetes cluster monitoring (via Prometheus)" is a cpu temperature graph included which querys `rpi_cpu_temperature_celsius`.  The query `rpi_cpu_temperature_celsius`seems not to exist.

**Comment by Gory19** [comment]
Did you enable "armExporter" in vars.jsonnet?

**Comment by Henrik-Wo** [comment]
yes

**Comment by carlosedp** [comment]
Check if the arm-exporter pods are running in your nodes, it's logs.
Check if arm-exporter appears in Prometheus targets.

**Comment by Henrik-Wo** [comment]
My mistake! I forgot to run a `make` after changing `vars.jsonnet`
