### ISSUE TITLE
arm-exporter: error reporting GPU temp

### ISSUE THREAD

**Issue by pascal71** [carlosedp/cluster-monitoring#73]
All arm-exporter PODs are up-and-running in the daemonset; however the logs show it is unable to access the GPU. Resulting log entries:

`time="2020-07-03T11:21:44Z" level=error msg="gpu collector failed after 0.003312s: exit status 255" source="collector.go:142"`

Doing a strace on the rpi_exporter binary shows that it tries to access /dev/vchiq. Which is not in /dev in the arm-exporter container of this POD.

Changing the securityContext to privileged for this POD (e.g. changing the arm-exporter-daemonset.yaml) fixes the problem.

Kind regards,

   Pascal van Dam

**Comment by carlosedp** [comment]
Would you submit a PR? What changes you did to the manifests?

**Comment by carlosedp** [comment]
Can you check if mounting the /dev from host to the pod fixes the problem?

**Comment by pascal71** [comment]
Will also do that :)


Will report back this evening, ok?

**Comment by pascal71** [comment]
Good evening Carlos,


I am afraid for mount /dev in a container you will still need the 
'privileged' security context. If you use that context, no need for 
mounting /dev as it's already working then.


E.g.:


    containers:
       - command:
         - /bin/rpi_exporter
         - --web.listen-address=127.0.0.1:9243
         image: carlosedp/arm_exporter:latest
         name: arm-exporter
/*   securityContext:*/*/
/**/          privileged: true/*
         resources:
           limits:
             cpu: 100m
             memory: 100Mi
           requests:
             cpu: 50m
             memory: 50Mi


Kind regards,


   Pascal van Dam

**Comment by carlosedp** [comment]
Yes, I think it's necessary since the utility that reads the temperature requires the device.
I'd welcome a PR!
Thanks

**Comment by pascal71** [comment]
Good afternoon,


Thank your for your reply.


I will, post one this evening.


Small other question;

als have ARM64 / RPI8Gb cluster running; that DOES report CPU (with priv 
mode) but not GPU temp.

Any idea?

**Comment by carlosedp** [comment]
No idea, I don't have the newer ones. I believe the vcgencmd utiity used by rpi_exporter doesn't support Rpi4 new SOC. Maybe Lukas from the rpi_exporter utility can help.
https://github.com/lukasmalkmus/rpi_exporter

**Comment by pascal71** [comment]
Good afternoon Carlos,


The arm7hf (32bit) does work for both CPU and GPU on RPi4. On ARM64 only 
for CPU.

I will contact Lukas. :)


Many thanks for your support.


Kind regards,


   Pascal van Dam

**Comment by carlosedp** [comment]
Closing this as it's not a monitoring stack issue.

**Comment by pascal71** [comment]
I will submit a PR for this
the solution is to add:

 container.mixin.securityContext.withPrivileged(true)

to

arm_exporter.jsonnet

**Comment by carlosedp** [comment]
Great, thanks for the find!
