### ISSUE TITLE
Prometheus.<node_ip>.nip.io is unreachable

### ISSUE THREAD

**Issue by nwber** [carlosedp/cluster-monitoring#81]
Can't reach Prometheus/Grafana/Alertmanager. I'm running a k3s cluster of 4 Raspberry Pi 4s, each running Raspberry Pi OS Lite.

<img width="746" alt="Screen Shot 2020-08-02 at 7 58 00 PM" src="https://user-images.githubusercontent.com/68207067/89135330-c6c60480-d4fa-11ea-9c7d-c11c509b1988.png">

My cluster is healthy and my nodes and master are all available. 

<img width="396" alt="Screen Shot 2020-08-02 at 8 10 04 PM" src="https://user-images.githubusercontent.com/68207067/89135527-456f7180-d4fc-11ea-85da-04f272d2ae9c.png">

I've opened both ports 80 + 443 on both my master and node (via ufw). 

The output of `kubectl get ingress --all-namespaces` and my `vars.jsonnet` file:

<img width="704" alt="ingress+vars_monitoring_rpi" src="https://user-images.githubusercontent.com/68207067/89135286-941c0c00-d4fa-11ea-84e9-0eb43bdf1534.png">

I've followed the steps for the k3s quickstart. There isn't much in the way of troubleshooting in the readme, so I'm a bit stuck.

**Comment by carlosedp** [comment]
Are you using K3s? Are the ingress pods (Traefik) running? Are you able to access any published application in the cluster, like a simple NGINX?
Have you tried setting the ingress suffix with the same IP as the master IP?

**Comment by nwber** [comment]
Yes, I'm running k3s. Here are my pods. As you can see, I got the standard Kubernetes Dashboard working (ignore `my-release-nginx`, I accidentally tried using an x86 helm chart):

<img width="791" alt="Screen Shot 2020-08-03 at 7 50 50 PM" src="https://user-images.githubusercontent.com/68207067/89238231-5931db00-d5c3-11ea-924f-ed59b0db5d6d.png">

I changed my ingress suffix to 10.0.0.9 and re-did the `make` & `kubectl apply` commands, still doesn't work:

<img width="537" alt="Screen Shot 2020-08-03 at 8 04 12 PM" src="https://user-images.githubusercontent.com/68207067/89238650-cb56ef80-d5c4-11ea-9850-a5081aaf80d4.png">

My Kubernetes Dashboard:

<img width="1240" alt="Screen Shot 2020-08-03 at 8 11 36 PM" src="https://user-images.githubusercontent.com/68207067/89238895-9b5c1c00-d5c5-11ea-89d8-ca72506ae661.png">

**Comment by carlosedp** [comment]
I see that your master has the IP 10.0.0.9 and the ingresses point to 10.0.0.10.nip.io. Might be your problem.
Other than that, you might need to investigate further on the infrastructure.

**Comment by nwber** [comment]
I figured it out: In the quickstart, I did the steps manually instead of `make deploy`. Running `make deploy` worked. Not sure why but it did 🤷‍♂️
