### ISSUE TITLE
Prometheus queries return nothing 

### ISSUE THREAD

**Issue by exArax** [carlosedp/cluster-monitoring#89]
Hello,

This is the first time that happened to me, everything under the monitoring is in running state but when I query prometheus returns empty results. Grafana also shows empty results. What went wrong?

**Comment by carlosedp** [comment]
You need to check Prometheus targets if they are connected to the collectors.

**Comment by exArax** [comment]
How could I perform a check like this?

**Comment by carlosedp** [comment]
Go into Prometheus web GUI, Status -> Targets. They all should be in "UP" state.

Similar to this:

![image](https://user-images.githubusercontent.com/20382/90772509-0f3b3b80-e2cb-11ea-86c7-fe7d6672faf2.png)

**Comment by exArax** [comment]
I made a make teardown. 
192.168.1.2 is the IP of the master node
192.168.3 and 192.168.1.3 are worker nodes
Again the prometheus IP is responding with an "Your connection was interruptedA network change was detected.
ERR_NETWORK_CHANGED" error

![Screenshot from 2020-08-20 20-16-17](https://user-images.githubusercontent.com/56536805/90804075-61f41200-e322-11ea-823f-7b1971768bec.png)

**Comment by carlosedp** [comment]
Sorry, you need to debug what's wrong in the cluster not the stack.
You should point the URL IP (in nip.io) to the IP your ingress controller runs.
