### ISSUE TITLE
Setup with MetalLB (and possibly an ingress/proxy) instead of nip.io

### ISSUE THREAD

**Issue by fourstepper** [carlosedp/cluster-monitoring#90]
Hi,

I am currently trying to figure out how I could approach deploying this stack on my RPi 4s running k8s (via kubeadm).

I am not 100% familiar with what the best practice could be here, but I have a working MetalLB load balancer which I can use to lease addresses. I would be okay with using one of the addresses and then the subdomain for each service.

Could you give me a pointer in which direction I should head this/example theoretical setup?

Thanks!

**Comment by carlosedp** [comment]
I wrote an article a while back about deploying into a similar cluster.
https://itnext.io/creating-a-full-monitoring-solution-for-arm-kubernetes-cluster-53b3671186cb?source=---------17------------------

Closing as it's not a stack issue.
