### ISSUE TITLE
Add `hacktoberfest` topic/label to the repo

### ISSUE THREAD

**Issue by NicklasWallgren** [carlosedp/cluster-monitoring#95]
It would be great to add a `hacktoberfest` label to the repo so that it appears on https://hacktoberfest.digitalocean.com/

**Comment by carlosedp** [comment]
Apparently it's not needed:

>  PRs can be made to any public repo on GitHub, not only the ones with issues labeled Hacktoberfest.

**Comment by NicklasWallgren** [comment]
@carlosedp They have updated the rules https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by carlosedp** [comment]
Done!
